version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./audio:/opt/audio
    links:
      - dict
  dict:
    build: .
    restart: always
    volumes:
      - ./cache.json:/opt/nodeapp/cache.json

